### ISSUE TITLE
Null pointer exception with recyclerview

### ISSUE THREAD

**Issue by alexdao** [Flipboard/bottomsheet#57]
I'm wrapping BottomSheetLayout around a LinearLayout that contains a RecyclerView (which is populated with RelativeLayouts). To test it, I'm calling 

    BottomSheetLayout bottomSheet = (BottomSheetLayout) v.findViewById(R.id.bottomsheet);
        bottomSheet.showWithSheetView(inflater.inflate(R.layout.fragment_layout, bottomSheet, false));

at the end of the fragment's onCreateView(), after the recyclerview has already been set up. 

However, this ends up breaking the RecyclerView, as any touch input causes this stack trace:

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
            at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:1540)
            at android.view.View.canScrollVertically(View.java:12835)
            at android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:35)
            at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:1161)
            at android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1575)
            at android.support.v4.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:643)
            at android.support.v4.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:657)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward

Here's a screenshot of what happens:

![image](https://cloud.githubusercontent.com/assets/5762765/9708898/8e42ce3e-54f0-11e5-9e2c-19c59af43674.png)

**Comment by hzsweers** [comment]
I don't think this is a bug on our end. I can't say for sure from looking at your stacktrace what's wrong with it (I'm able to use recyclerview in a sheet just fine on an internal project).

I would hazard a guess though that it has something to do with `SwipeRefreshLayout`, which would almost certainly not work as desired with bottom sheet. Not too familiar with its implementation under the hood, but I could imagine a case where it tries to get a view under a certain x/y position and (perhaps mistakenly) assumes that result is never null. Try removing that wrapper and see if that helps.

**Comment by alexdao** [comment]
You were right! Removing the ScrollView fixed the NullPointerException. 
My data to populate the RecyclerView still isn't showing though. I'm fetching it via an Otto event. Do you have any idea why adding BottomSheetLayout would cause this?

**Comment by hzsweers** [comment]
I have no idea :/. Could you share a snippet of your fragment_layout file or overview of your view hieararchy? FWIW I had trouble when trying to nest it in a nestedscrollview (Google can't seem to make up their mind on if they support this or not).

**Comment by alexdao** [comment]
Sure! Here's my fragment_layout file:

    <com.flipboard.bottomsheet.BottomSheetLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/bottomsheet"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/linear_layout_base"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:context="com.lumivote.lumivote.ui.votes_tab.VotesFragment">


            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_alignParentTop="true"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />


        <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/relative_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?android:attr/selectableItemBackground"
            android:orientation="horizontal"
            android:paddingBottom="@dimen/rv_padding">

            <TextView
                android:id="@+id/leftTitle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                android:paddingLeft="@dimen/rv_padding"
                android:paddingRight="@dimen/padding_between_main_and_right"
                android:paddingTop="@dimen/rv_padding"
                android:textSize="@dimen/main_text_size" />

            <TextView
                android:id="@+id/leftDescription"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_below="@id/leftTitle"
                android:paddingLeft="@dimen/rv_padding"
                android:paddingRight="@dimen/padding_between_main_and_right"
                android:textSize="@dimen/description_text_size"
                android:textStyle="italic" />

            <TextView
                android:id="@+id/mainTitle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentTop="true"
                android:paddingEnd="@dimen/rv_padding"
                android:paddingRight="@dimen/rv_padding"
                android:paddingTop="@dimen/rv_padding"
                android:textSize="@dimen/main_text_size" />

            <TextView
                android:id="@+id/mainDescription"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:paddingEnd="@dimen/rv_padding"
                android:paddingRight="@dimen/rv_padding"
                android:textSize="@dimen/description_text_size" />

        </RelativeLayout>

    </LinearLayout>
</com.flipboard.bottomsheet.BottomSheetLayout>

Also, I don't know if this is weird but I noticed you graduated from UT last year... I'm from Plano, so I have a lot of friends that go to UT haha

**Comment by hzsweers** [comment]
Not weird at all, world needs more Texans :)

So looking at that, nothing stands out to me as an obvious reason why it might not be loading, especially if you're able to get the sheet showing without any problems. My suggested debugging steps would be as follows:

* Breakpoint your adapter and see if the appropriate `onBindViewHolder` and `onCreateViewHolder` methods are actually being hit.
* Remove the sheet wrapper and see if it still doesn't work

Also, I just realized that you're not trying to put the recyclerview *in* the sheet, which totally changes things. You can enable interacting with views outside the sheet via `BottomSheetLayout#setInterceptContentTouch(boolean)`, then your swipe refresh layout should hopefully work since the sheet won't intercept those touches.. Sorry for the confusion!

**Comment by alexdao** [comment]
Hm, alright, thanks for your help and quick responses anyways. I guess I'll spend the rest of the night figuring this out :+1: 

Feel free to close the issue since it seems to be a problem on my end

**Comment by hzsweers** [comment]
Happy to help. Let me know if disabling the interceptContentTouch flag fixes the initial issue as well

**Comment by alexdao** [comment]
Finally figured it out!!! Issue was having the RecyclerView item layout in the fragment layout itself. I moved it out into a separate file to inflate within `onCreateViewHolder()`. 

Doing it this way also means the `SwipeRefreshLayout` now works without disabling the interceptContent Touch flag

**Comment by hzsweers** [comment]
Good to hear, glad you were able to figure it out!

**Comment by alexdao** [comment]
I'll see if I can make some contributions to BottomSheet after I finish my project. This seems like a fun lib to work on

**Comment by hzsweers** [comment]
Contributions are always welcome! Take a look at the issue tracker to see some of the implementations we're looking to add in the near future

**Comment by yanbin92** [comment]
you use RecyclerView  must use a LayoutManager,
such as 
`   LinearLayoutManager layoutManager = new LinearLayoutManager(context);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        mRecyclerView.setLayoutManager(layoutManager);`
i meet the same problem and solve the problem .
