### ISSUE TITLE
Get this OOB exception

### ISSUE THREAD

**Issue by 29jitender** [Flipboard/bottomsheet#72]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{35dc8731 position=1 id=-1, oldPos=-1, pLpos:-1 scrap tmpDetached no parent}
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(SourceFile:4349)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4480)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4461)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile:1962)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1371)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1334)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:563)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:2847)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3145)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.support.v4.view.ViewPager.onLayout(SourceFile:1627)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.support.design.widget.CoordinatorLayout.layoutChild(SourceFile:1034)
       at android.support.design.widget.CoordinatorLayout.onLayoutChild(SourceFile:744)
       at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:758)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at com.flipboard.bottomsheet.BottomSheetLayout.onLayout(SourceFile:205)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by hzsweers** [comment]
This isn't a bottomsheet issue, rather it's an issue with your recyclerview+adapter+layoutmanager. This can happen when you try to animate in new items while scroll is occuring
